[package]
name = "maybe-ggez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.0-rc"
keyframe = "1.1.1"
keyframe_derive = "1.0.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
